### ISSUE TITLE
potentially insecure hash functions not allowed

### ISSUE THREAD

**Issue by amirtgm** [libp2p/js-libp2p-delegated-content-routing#95]
when i'm trying to provide a simple JSON object as below:
```ts
const delegatedContentRouting = new DelegatedContentRouting(
    ipfsHttpClient({
      host: 'node0.delegate.ipfs.io', // In production you should setup your own delegates
      protocol: 'https',
      port: 443,
      timeout: '50000ms',
    })
  );
  const LIBP2P_KEY_CODE = 0x0200;
  const buff = JSON.stringify({
    title: 'asdasdas',
  });
  const datas = multihashes.encode(Buffer.from(buff), 'sha2-256');

  const cid = CID.createV1(LIBP2P_KEY_CODE, Digest.create(LIBP2P_KEY_CODE, datas));
  delegatedContentRouting
    .provide(cid as any)
    .then(console.log)
    .catch(console.log);
```
It throws the error of insecure hash function
```log
HTTPError: potentially insecure hash functions not allowed
    at Object.errorHandler [as handleError] (core.js:103:1)
    at async Client.fetch (http.js:149:1)
    at async Object.stat (stat.js:15:1)
    at async index.ts:140:1
    at async run (index.js:109:1)
```

**Comment by achingbrain** [comment]
`0x0200` is the json multicodec and cannot be used as a hash type.

Try this instead:

```js
import { DelegatedContentRouting } from '@libp2p/delegated-content-routing'
import { CID } from 'multiformats/cid'
import { sha256 } from 'multiformats/hashes/sha2'
import { create as ipfsHttpClient } from 'ipfs-http-client'

const delegatedContentRouting = new DelegatedContentRouting(
  ipfsHttpClient({
    host: 'node0.delegate.ipfs.io', // In production you should setup your own delegates
    protocol: 'https',
    port: 443,
    timeout: '50000ms',
  })
);
const JSON_CODEC = 0x0200;
const buff = JSON.stringify({
  title: 'asdasdas',
});
const datas = sha256.digest(Buffer.from(buff))

const cid = CID.createV1(JSON_CODEC, datas);
delegatedContentRouting
  .provide(cid)
  .then(console.log)
  .catch(console.log);
```
